// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzhjdbexqpzzrzwvirrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6aGpkYmV4cXB6enJ6d3ZpcnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDA3MjYsImV4cCI6MjA3MjgxNjcyNn0.D2FDHYrfYt16_hcioa3Ni3EtZY9gf-b8OAJk8wYmjxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});